# Generated by Django 2.1.5 on 2019-02-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_text',
            field=models.TextField(),
        ),
    ]
